name: w_cli
description: A command-line tool for Flutter projects, including API code generation and app building.
version: 1.0.14
homepage: https://github.com/stone0533/w_cli
repository: https://github.com/stone0533/w_cli
issue_tracker: https://github.com/stone0533/w_cli/issues
documentation: https://github.com/stone0533/w_cli/wiki

environment:
  sdk: ^3.10.3

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  args: ^2.4.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

# Include additional files in the published package
files:
  - bin/**
  - lib/**
  - CHANGELOG.md
  - LICENSE
  - README.md

# 声明资源文件
resources:
  - lib/sh/api_gen.sh
  - lib/sh/build.sh
  - lib/sh/open.sh
  - lib/sh/setup_project.sh

# Define executable name
executables:
  ww: w_cli

